### ISSUE TITLE
No such module, when importing Sage in playground

### ISSUE THREAD

**Issue by Sajjon** [nvzqz/Sage#2]
Hi, I am very excited about this project! 👍 

I git clone master branch and opened the _Playground_ but I get a compile error on the
```swift
import Sage
```
Line, with the error "No such module 'Sage'". 

Any ideas?

**Comment by nvzqz** [comment]
You need to open `Sage.xcodeproj`, build it, and then go to the playground file from within the Xcode project.

For some reason Xcode 8 doesn't want to run any of the library's code, but it works correctly in Xcode 7.

**Comment by Sajjon** [comment]
Ah I had to build the Sage OSX and not iOS target! Maybe this info can be added to the installation README? ;)

Thanks!

**Comment by nvzqz** [comment]
The default platform for the playground is OS X, but you can change it to iOS or tvOS. I'll definitely clarify this in the readme, thanks!

**Comment by nvzqz** [comment]
Added 17d2bd91e9a78edbec4a1ba2bc657e9db0a5c0c9
