### ISSUE TITLE
No UIView class for Chess Board. OR am i getting this wrongly

### ISSUE THREAD

**Issue by iAviatorJose** [nvzqz/Sage#9]
i have added your library as a pod to my project.
But i don't find any Chess BoardView

Apologies if this is a naive Question

**Comment by nvzqz** [comment]
There is no `BoardView` class, sorry. You could use the playground view, but that was only really for working with Xcode playgrounds. I would suggest creating your own `UIView`.

**Comment by iAviatorJose** [comment]
@nvzqz thank you
